AppBundle\Entity\BaseEntity:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        createdAt:
            expose: true
        updatedAt:
            expose: true
        deleted:
            expose: false