AppBundle\Entity\TipoEvento:
    type: entity
    table: tipo_evento
    repositoryClass: AppBundle\Repository\TipoEventoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            length: 255
        salida:
            type: boolean
            nullable: true
            options:
                default: false
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
        deleted:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
    oneToMany:
        eventoHidricos:
            targetEntity: AppBundle\Entity\EventoHidrico
            mappedBy: tipoEvento